architect:
  - ardesco
  - afranken
  - pmouawad
docker:
  image: "yegor256/rultor-image"
decrypt:
  settings.xml: "repo/settings.xml.asc"
env:
  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
release:
  pre: false
  script: |-
    mvn -Prelease versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Prelease --settings /home/r/settings.xml
  commanders:
    - ardesco
    - pmouawad
