architect:
  - ardesco
  - afranken
  - pmouawad
docker:
  image: "yegor256/rultor-image"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
env:
  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
release:
  pre: false
  script: |-
    mkdir /home/r/gpg/
    cp ../.gnupg/pubring.kbx /home/r/gpg/pubring.kbx
    whoami
    ls -la /home/r/gpg/
    sudo chown -R r /home/r/gpg/
    sudo chmod -R 600 /home/r/gpg/
    mvn -Prelease versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    whoami
    ls -la /home/r/gpg/
    mvn clean deploy -Prelease --settings /home/r/settings.xml
  commanders:
    - ardesco
    - pmouawad
